### ISSUE TITLE
styled(Col)`some-styles` does not work

### ISSUE THREAD

**Issue by yaplas** [securityscorecard/design-system#88]
https://github.com/securityscorecard/design-system/blob/26ec617d6f08d81117fa4f0125ac155a144ccfb7/src/components/layout/Col/Col.tsx#L27

I don't know if this is intentional but we can't add styles to a Col component for instance to align content to right, seems annoying to have to add an extra child component to do this. Looks like "className" prop is hidden. I mean something like this could work: 
```
const Col: React.FC<ColProps> = styled(Box).attrs(({ children, cols, offset }) => ({
  ml: `${(100 / 12) * offset}%`,
  ...getColWidth(cols),
  children,
})`
  padding-left: ${getColPadding};
  padding-right: ${getColPadding};
`;
```

**Comment by ajkl2533** [comment]
Hi @yaplas good point we'll fix it 👍
